// <auto-generated />
using System;
using HL.Diners.Infrastructure.EfData;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace HL.Diners.Infrastructure.Migrations
{
    [DbContext(typeof(DinersContext))]
    [Migration("20181004185709_10418-4")]
    partial class _104184
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("HL.Diners.Core.Model.Bucket", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Created");

                    b.Property<string>("CycleId");

                    b.Property<DateTime>("Modified");

                    b.Property<string>("Name");

                    b.Property<int>("Target");

                    b.Property<int>("Used");

                    b.HasKey("Id");

                    b.HasIndex("CycleId");

                    b.ToTable("Bucket");
                });

            modelBuilder.Entity("HL.Diners.Core.Model.Cycle", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("Budget");

                    b.Property<DateTime>("Created");

                    b.Property<DateTime>("EndDate");

                    b.Property<string>("ExtendedData");

                    b.Property<DateTime>("Modified");

                    b.Property<double>("SavingsTarget");

                    b.Property<DateTime>("StartDate");

                    b.HasKey("Id");

                    b.ToTable("Cycles");
                });

            modelBuilder.Entity("HL.Diners.Core.Model.Bucket", b =>
                {
                    b.HasOne("HL.Diners.Core.Model.Cycle")
                        .WithMany("Buckets")
                        .HasForeignKey("CycleId");
                });
#pragma warning restore 612, 618
        }
    }
}
